name: Result Checker Bot

on:
  schedule:
    - cron: '30 2,4 * * *'
    - cron: '0,30 6-10 * * *'
    - cron: '30-59/5 10 * * *'
    - cron: '*/5 11-12 * * *'
    - cron: '0-30/5 13 * * *'
    - cron: '30 13,14,15 * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  check_results:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Checker Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python result_checker.py

      # --- NEW STEP: Upload Screenshot if Error ---
      - name: Upload Error Screenshot
        if: failure() || success()  # Run this even if the script crashed
        uses: actions/upload-artifact@v4
        with:
          name: error-debug
          path: error_screenshot.png
          if-no-files-found: ignore
